# Generated by Django 4.2.3 on 2023-07-21 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='create_date',
        ),
        migrations.AddField(
            model_name='comments',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 20, 11, 29, 668213, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_data',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 20, 11, 29, 667158, tzinfo=datetime.timezone.utc)),
        ),
    ]
