# Generated by Django 4.2.3 on 2023-07-21 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_create_data_post_created_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_data',
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 20, 16, 49, 350928, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 20, 16, 49, 350928, tzinfo=datetime.timezone.utc)),
        ),
    ]
